#!/bin/sh
set -e

set -- bash -c "cd /var/www && php artisan serve --host=0.0.0.0 --port=80" "$@"

# first arg is `-f` or `--some-option`
if [ "${OCTANE}" ] && [ "${OCTANE}" -eq 0 ]; then
	set -- bash -c "cd /var/www && php artisan serve --host=0.0.0.0 --port=80" "$@"
else
  set -- bash -c "cd /var/www && php artisan octane:start --server=swoole --watch --host=0.0.0.0 --port=80" "$@"
fi

exec "$@"
